import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Baby, BedDouble, CalendarDays, HeartPulse, MapPin, Phone, Search, UserRound } from "lucide-react";
import { articles, doctors, services } from "@/lib/data";
import { ArticleCard, Button, Container, DoctorCard, PartnerCategoryCard, ProcessSteps, SectionHeading, ServiceCard, TrustMetric } from "@/components/ui";

export default function Home() { return <>
  <section className="hero"><Container><div className="hero-grid"><div><p className="eyebrow">Rumah sakit untuk keluarga dan kota kita</p><h1>Perawatan yang dekat. Dampak yang lebih luas.</h1><p className="hero-copy">Nusa Medika menghadirkan layanan medis yang jelas, manusiawi, dan terkoordinasi, sekaligus membuka kemitraan terverifikasi bagi usaha lokal Indonesia.</p><div className="mt-7 flex flex-wrap gap-3"><Button href="/kontak#janji">Buat Janji <ArrowUpRight size={16} /></Button><Button href="/dokter" variant="secondary">Cari Dokter</Button></div><a href="tel:0215550119" className="mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[#B85E3F]">Butuh pertolongan segera? Hubungi IGD <Phone size={15} /></a></div><div className="hero-image"><Image src="https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=88" alt="Dokter berbicara dengan keluarga di ruang konsultasi rumah sakit" fill priority sizes="(max-width: 1023px) 100vw, 55vw" /><div className="hero-panel"><div><span>IGD</span><strong>24 jam</strong></div><div><span>Jadwal hari ini</span><strong>Poliklinik buka</strong></div><div><span>Lokasi</span><strong>Kota Sentosa</strong></div></div></div></div></Container></section>
  <Container className="-mt-8 relative z-10"><div className="quick-access"><Link className="quick-item" href="/dokter"><Search size={21} /><span><strong>Cari Dokter</strong><span>Temukan jadwal praktik</span></span></Link><Link className="quick-item" href="/layanan#jadwal"><CalendarDays size={21} /><span><strong>Jadwal Poliklinik</strong><span>Lihat hari dan waktu layanan</span></span></Link><Link className="quick-item" href="/kontak#informasi-pasien"><BedDouble size={21} /><span><strong>Informasi Rawat Inap</strong><span>Panduan untuk keluarga</span></span></Link><Link className="quick-item" href="tel:0215550119"><Phone size={21} /><span><strong>Hubungi IGD</strong><span>Tersedia sepanjang hari</span></span></Link></div></Container>
  <section className="section"><Container><SectionHeading eyebrow="Layanan medis" title="Yang Anda butuhkan, dengan alur yang jelas.">Pilih layanan sesuai kebutuhan. Tim kami membantu Anda memahami langkah berikutnya.</SectionHeading><div className="service-grid">{services.map(s => <ServiceCard key={s.id} service={s} />)}</div><div className="mt-7"><Button href="/layanan" variant="secondary">Lihat semua layanan <ArrowUpRight size={16} /></Button></div></Container></section>
  <section className="section section-sage"><Container><div className="pathway-grid"><div><SectionHeading title="Datang dengan lebih tenang">Informasi yang sederhana membuat persiapan kunjungan terasa lebih ringan.</SectionHeading><Button href="/kontak#janji">Mulai buat janji <ArrowUpRight size={16} /></Button></div><ProcessSteps steps={["Temukan dokter atau layanan", "Pilih jadwal kunjungan", "Siapkan data pendaftaran", "Datang sesuai waktu yang dipilih"]} /></div></Container></section>
  <section className="section"><Container><SectionHeading title="Standar yang kami jaga setiap hari.">Kami membangun rumah sakit yang dapat diandalkan melalui praktik klinis, sistem, dan komunikasi yang bertanggung jawab.</SectionHeading><div className="trust-band"><TrustMetric value="Contoh data" label="Akreditasi rumah sakit" /><TrustMetric value="Lintas spesialisasi" label="Tenaga medis dan layanan" /><TrustMetric value="24 jam" label="Layanan gawat darurat" /><TrustMetric value="Disiapkan" label="Arsitektur interoperabilitas kesehatan" /></div><p className="mt-5 max-w-2xl text-xs leading-5 text-[#5F6A67]">Arsitektur sistem disiapkan untuk mengikuti standar interoperabilitas kesehatan yang berlaku. Informasi ini adalah konten demonstrasi, bukan klaim akreditasi atau integrasi aktif.</p></Container></section>
  <section className="section section-ivory"><Container><div className="flex items-end justify-between gap-6"><SectionHeading eyebrow="Dokter kami" title="Dokter yang tepat, jadwal yang jelas." /><Link href="/dokter" className="hidden shrink-0 text-sm font-bold text-[#1E6767] sm:block">Lihat direktori dokter <ArrowUpRight className="inline" size={15} /></Link></div><div className="doctor-grid">{doctors.slice(0, 4).map(d => <DoctorCard key={d.id} doctor={d} />)}</div><Link href="/dokter" className="mt-6 block text-sm font-bold text-[#1E6767] sm:hidden">Lihat direktori dokter <ArrowUpRight className="inline" size={15} /></Link></Container></section>
  <section className="section"><Container><div className="partner-feature"><div className="partner-graphic"><div className="partner-quote"><p className="eyebrow text-[#F5C3A9]">Mitra Nusa</p><blockquote>Rumah sakit bertumbuh bersama usaha lokal.</blockquote><cite>Program kemitraan non-klinis Nusa Medika</cite></div></div><div><SectionHeading title="Kemitraan dengan standar yang jelas.">Kami membuka peluang pengadaan non-klinis bagi UMKM yang memiliki identitas usaha, kapasitas produksi, serta komitmen terhadap mutu dan ketepatan layanan.</SectionHeading><div className="category-grid">{["Konsumsi dan katering", "Linen dan produk tekstil", "Perlengkapan pasien", "Furnitur dan interior", "Percetakan dan merchandise", "Pemeliharaan fasilitas"].map(x => <PartnerCategoryCard key={x} label={x} />)}</div><div className="mt-7 flex flex-wrap gap-3"><Button href="/mitra-nusa">Pelajari Mitra Nusa <ArrowUpRight size={16} /></Button><Button href="/mitra-nusa#daftar" variant="secondary">Daftarkan Usaha</Button></div></div></div></Container></section>
  <section className="section section-sage"><Container><div className="impact-wrap"><div><p className="eyebrow">Dampak komunitas</p><div className="impact-number">4.280</div><p className="mt-3 text-sm font-semibold text-[#123F42]">peserta skrining komunitas<br /><span className="font-normal text-[#5F6A67]">contoh data tahun berjalan</span></p></div><div className="trust-band"><TrustMetric value="18" label="Mitra UMKM terverifikasi" /><TrustMetric value="32%" label="Belanja non-klinis lokal" /><TrustMetric value="12" label="Program edukasi masyarakat" /><TrustMetric value="4.280" label="Peserta skrining komunitas" /></div></div></Container></section>
  <section className="section"><Container><SectionHeading title="Catatan kesehatan untuk keluarga.">Informasi edukatif, bukan diagnosis. Konsultasikan kondisi Anda kepada tenaga medis.</SectionHeading><div className="article-grid">{articles.map((a, i) => <ArticleCard key={a.title} article={a} index={i} />)}</div></Container></section>
  <Container className="pb-24"><div className="cta-block"><div><h2>Rencanakan kunjungan tanpa terburu-buru.</h2><p>Kami siap membantu Anda menemukan layanan dan jadwal yang sesuai.</p></div><div className="flex shrink-0 flex-wrap gap-3"><Button href="/kontak#janji" variant="secondary">Buat Janji</Button><Button href="/kontak" variant="quiet" className="text-white">Hubungi Kami</Button></div></div></Container>
  <div className="sr-only"><UserRound /><HeartPulse /><Baby /><MapPin /></div>
</> }
