import Image from "next/image";
import Link from "next/link";
import { menuItems } from "@/data/menu";
import { partners } from "@/data/partners";
import { matches } from "@/data/matches";
import { testimonials } from "@/data/testimonials";
import { site } from "@/data/site";
import { AnnouncementBar, AvailabilityBadge, MenuCard, SectionHeading, WhatsAppButton } from "@/components/ui";

export default function Home() { const next = matches[0]; return <>
  <AnnouncementBar />
  <section className="container grid min-h-[620px] grid-cols-1 gap-8 py-8 lg:grid-cols-[.88fr_1.12fr] lg:items-stretch lg:py-10">
    <div className="flex flex-col justify-center pb-4 lg:py-10"><p className="eyebrow mb-5">{site.descriptor}</p><h1 className="display max-w-xl text-6xl leading-[.88] sm:text-7xl lg:text-[6.4rem]">Makan dekat.<br/><span className="text-sambal">Nonton lekat.</span></h1><p className="mt-7 max-w-md text-base leading-7 text-muted">Angkringan indoor untuk nasi hangat, gorengan baru turun, dan sembilan puluh menit yang dirayakan ramai-ramai.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="button button-red" href="/nobar">Lihat Jadwal Nobar</Link><Link className="button button-light" href="/menu">Buka Menu</Link></div><div className="mt-12 grid max-w-md grid-cols-3 gap-4 border-t border-charcoal/20 pt-4 text-xs font-bold"><span>Mulai<br/><strong className="mt-1 block text-base tabular">Rp3 ribuan</strong></span><span>Tempat<br/><strong className="mt-1 block text-base">Indoor & lesehan</strong></span><span>Belanja<br/><strong className="mt-1 block text-base">Mitra sekitar</strong></span></div></div>
    <div className="photo hand-border min-h-[440px] lg:min-h-0"><Image src={site.images.hero} alt="Warga Indonesia duduk lesehan menikmati nobar bola di dalam angkringan Lungguh" fill priority sizes="(max-width: 1024px) 100vw, 54vw"/><div className="absolute bottom-5 left-5 z-10 max-w-[230px] bg-paper px-4 py-3 text-sm font-bold leading-5">Layar besar, tikar bersih, sambal terus jalan.</div></div>
  </section>

  <section className="section-pad texture"><div className="container"><SectionHeading eyebrow="Yang turun ke meja" title="Pesan satu dulu. Nanti tambah." copy="Menu kecil-kecil untuk makan santai, ngobrol panjang, atau menemani peluit awal." href="/menu" link="Lihat semua menu"/><div className="mt-10 grid grid-cols-2 gap-x-4 gap-y-10 md:grid-cols-3">{menuItems.slice(0,6).map(item=><MenuCard key={item.name} item={item}/>)}</div></div></section>

  <section className="section-pad bg-charcoal text-paper"><div className="container grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow text-warung">Nobar pekan ini</p><h2 className="display mt-4 max-w-lg text-5xl leading-[.92] sm:text-6xl">Layar besar.<br/>Suara ramai.<br/><span className="text-warung">Sambal tetap jalan.</span></h2><p className="mt-6 max-w-md leading-7 text-paper/70">Pesan tempat sebelum peluit awal. Kapasitas lesehan kami terbatas supaya layar tetap terlihat dari semua sisi.</p><Link className="button button-red mt-8" href="/reservasi">Pesan Tempat</Link></div><div className="border border-paper/20 bg-paper/5 p-5 sm:p-8"><div className="flex items-center justify-between border-b border-paper/15 pb-5"><span className="text-xs font-bold uppercase tracking-[.18em] text-paper/60">Pertandingan berikutnya</span><AvailabilityBadge status={next.status}/></div><div className="py-8"><p className="text-sm text-paper/60">{next.competition} · {next.date}</p><p className="display mt-3 text-4xl sm:text-6xl">{next.home} <span className="text-warung">vs</span> {next.away}</p></div><div className="grid grid-cols-3 border-t border-paper/15 pt-5 text-sm"><span>Kick-off<strong className="mt-1 block text-lg tabular text-warung">{next.kickoff}</strong></span><span>Pintu buka<strong className="mt-1 block text-lg tabular text-warung">{next.doors}</strong></span><span>Kursi tersisa<strong className="mt-1 block text-lg tabular text-warung">{next.seats} kursi</strong></span></div><p className="mt-6 text-xs leading-5 text-paper/55">Datang 45 menit sebelum kick-off · Tidak ada minimum order yang memberatkan</p></div></div></section>

  <section className="section-pad"><div className="container grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="photo aspect-[4/3] hand-border"><Image src={site.images.interior} alt="Interior angkringan indoor dengan meja rendah, tikar anyaman, dan layar proyektor" fill sizes="(max-width: 1024px) 100vw, 52vw"/></div><div><p className="eyebrow">Lesehan indoor</p><h2 className="display mt-4 text-5xl leading-[.92] sm:text-6xl">Rumah yang siap menampung ramai.</h2><p className="prose-copy mt-6">Hujan boleh turun, obrolan jangan. Lungguh dirancang seperti ruang tengah bersama: meja rendah, bantal secukupnya, kipas yang bekerja, dan pandangan layar yang tidak terhalang.</p><div className="mt-8 grid gap-4 border-t border-charcoal/20 pt-5 text-sm sm:grid-cols-3">{["Teduh saat hujan","Pandangan layar tidak terhalang","Sendiri atau serombongan"].map((x,i)=><div key={x}><span className="font-mono text-xs text-sambal">0{i+1}</span><p className="mt-2 font-bold leading-5">{x}</p></div>)}</div></div></div></section>

  <section className="section-pad bg-rice"><div className="container"><SectionHeading eyebrow="Belanja kami tidak pergi jauh" title="Meja kami disokong tetangga." copy="Bahan harian datang dari dapur dan pemasok sekitar. Bukan jargon—ini daftar belanjanya."/><div className="mt-10 grid gap-0 border-y border-charcoal/20 sm:grid-cols-2 lg:grid-cols-4">{partners.map((p,i)=><div className="border-b border-charcoal/20 p-6 sm:nth-[odd]:border-r lg:border-b-0 lg:border-r lg:last:border-r-0" key={p.name}><p className="font-mono text-xs text-sambal">0{i+1}</p><h3 className="display mt-6 text-2xl">{p.name}</h3><p className="mt-3 text-sm font-bold">{p.offer}</p><p className="mt-3 text-sm leading-6 text-muted">{p.detail}</p></div>)}</div></div></section>

  <section className="section-pad"><div className="container"><SectionHeading eyebrow="Kata yang terdengar di tikar" title="Yang penting: betah."/><div className="mt-10 grid gap-0 border-y border-charcoal/20 md:grid-cols-3">{testimonials.map((quote,i)=><blockquote key={quote} className="border-b border-charcoal/20 p-6 md:border-b-0 md:border-r md:last:border-r-0"><span className="text-4xl text-sambal">“</span><p className="mt-3 text-lg font-bold leading-7">{quote}</p><footer className="mt-5 text-xs font-bold uppercase tracking-wider text-muted">Pengunjung Lungguh · {i+1}</footer></blockquote>)}</div></div></section>

  <section className="section-pad border-t border-line"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="eyebrow">Mampir ke rumah</p><h2 className="display mt-4 text-5xl leading-[.92]">Dekat dari jalan pulang.</h2><p className="mt-5 text-muted">Jl. Contoh No. 17, Kecamatan Contoh, Yogyakarta</p><p className="mt-3 text-sm font-bold">Setiap hari · 10.00–23.00 WIB</p><Link href="/lokasi" className="button button-dark mt-7">Lihat lokasi</Link></div><div className="map-grid relative flex min-h-[280px] items-end overflow-hidden border border-charcoal/30 bg-rice p-6"><div className="absolute inset-0 opacity-50" style={{backgroundImage:"linear-gradient(25deg,transparent 46%,#b9a88d 47%,#b9a88d 49%,transparent 50%),linear-gradient(110deg,transparent 48%,#b9a88d 49%,#b9a88d 51%,transparent 52%),linear-gradient(#d8c9b0 1px,transparent 1px),linear-gradient(90deg,#d8c9b0 1px,transparent 1px)",backgroundSize:"100% 100%,100% 100%,42px 42px,42px 42px"}}/><div className="relative border border-charcoal bg-paper px-4 py-3 text-sm font-bold shadow-[4px_4px_0_var(--charcoal)]">Lungguh<br/><span className="text-xs font-normal text-muted">titik lokasi pengganti</span></div></div></div></section>

  <section className="texture border-t border-line"><div className="container flex flex-col gap-6 py-14 md:flex-row md:items-center md:justify-between"><div><p className="eyebrow">Rame-rame? Bisa diatur.</p><h2 className="display mt-3 text-4xl sm:text-5xl">Bawa rombongan. Lapar biar kami yang urus.</h2></div><div className="flex flex-wrap gap-3"><Link className="button button-red" href="/reservasi">Pesan Tempat</Link><WhatsAppButton/></div></div></section>
</>; }
