import Image from "next/image";
import Link from "next/link";
import { services, salon, formatRupiah, whatsappUrl, testimonials, faqs } from "@/data/salon";
import { articles } from "@/data/journal";
import { Wordmark } from "./brand";
import { FaqAccordion, ServiceCategoryFilter } from "./interactive";

export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function SectionIntro({ eyebrow, title, copy, align = "left" }: { eyebrow?: string; title: string; copy?: string; align?: "left" | "center" }) { return <div className={`section-intro ${align === "center" ? "text-center" : ""}`}>{eyebrow && <Eyebrow>{eyebrow}</Eyebrow>}<h2>{title}</h2>{copy && <p>{copy}</p>}</div>; }
export function ImageWithCaption({ src, alt, caption, ratio = "landscape" }: { src: string; alt: string; caption?: string; ratio?: string }) { return <figure className={`image-figure ${ratio}`}><Image src={src} alt={alt} fill sizes="(max-width: 768px) 100vw, 50vw" /><span className="image-grain" />{caption && <figcaption>{caption}</figcaption>}</figure>; }

export function FeaturedTreatments() { return <div className="treatment-list">{services.filter(s => ["Hair Cut & Styling", "Hair Spa", "Hair Color", "Facial Care", "Manicure & Pedicure", "Head, Neck & Shoulder Relaxation"].includes(s.name)).map((service, i) => <article className="treatment-row" key={service.name}><span className="row-number">0{i + 1}</span><div><h3>{service.name}</h3><p>{service.description}</p></div><div className="treatment-meta"><span>{service.duration}</span><strong>Mulai {formatRupiah(service.price)}</strong></div><Link href="/layanan" aria-label={`Lihat detail ${service.name}`}>↗</Link></article>)}</div>; }

export function ServiceList() { return <><ServiceCategoryFilter /><div className="service-menu">{services.map((service) => <article className="service-item" data-category={service.category} key={service.name}><div className="service-item-title"><span className="service-category">{service.category}</span><h2>{service.name}</h2></div><p>{service.description}</p><div className="service-item-meta"><span>{service.duration}</span><strong>Mulai {formatRupiah(service.price)}</strong></div>{service.note && <small>{service.note}</small>}<a className="text-link" href={whatsappUrl(salon.bookingTemplates.service.replace("{service}", service.name))} target="_blank" rel="noreferrer">Tanyakan jadwal <span>↗</span></a></article>)}</div><p className="fine-print">Biaya akhir dapat menyesuaikan panjang rambut, penggunaan produk, tingkat pengerjaan, dan hasil konsultasi.</p></>; }

export function Testimonials() { return <div className="testimonial-grid">{testimonials.map((item) => <blockquote className="testimonial" key={item.name}><span className="quote-mark">“</span><p>{item.quote}</p><footer><strong>{item.name}</strong><span>{item.detail}</span></footer></blockquote>)}</div>; }
export function JournalPreview() { return <div className="journal-preview">{articles.map((article, i) => <Link className="journal-card" href={`/jurnal/${article.slug}`} key={article.slug}><div className="journal-card-image"><Image src={article.hero} alt="" fill sizes="(max-width: 768px) 100vw, 33vw" /></div><div><span className="service-category">{article.category} · {article.readingTime}</span><h3>{article.title}</h3><p>{article.excerpt}</p><span className="text-link">Baca jurnal <span>↗</span></span></div><span className="row-number">0{i + 1}</span></Link>)}</div>; }

export function SalonDetails() { return <div className="details-grid"><div><Eyebrow>Datang berkunjung</Eyebrow><h2>{salon.contact.address}</h2><a href={salon.contact.mapsUrl} target="_blank" rel="noreferrer" className="text-link">Buka di Google Maps ↗</a></div><div><Eyebrow>Jam buka</Eyebrow><ul className="hours">{salon.hours.map(([day, time]) => <li key={day}><span>{day}</span><strong>{time}</strong></li>)}</ul></div><div><Eyebrow>Hubungi kami</Eyebrow><a className="contact-big" href={whatsappUrl(salon.bookingTemplates.general)} target="_blank" rel="noreferrer">{salon.contact.displayWhatsapp}</a><a href={`tel:${salon.contact.phone.replaceAll(" ", "")}`}>{salon.contact.phone}</a><a href={salon.contact.instagramUrl} target="_blank" rel="noreferrer">{salon.contact.instagram}</a></div></div>; }
export function FAQSection() { return <FaqAccordion items={faqs} />; }
export function Footer() { return <footer className="site-footer"><div className="footer-main"><div><Wordmark /><p>Perawatan yang terasa personal,<br />dengan ruang untuk bernapas.</p></div><div><Eyebrow>Navigasi</Eyebrow><div className="footer-links">{salon.nav.map(([label, href]) => <Link href={href} key={href}>{label}</Link>)}</div></div><div><Eyebrow>Temui kami</Eyebrow><p>{salon.contact.address}</p><a href={salon.contact.instagramUrl} target="_blank" rel="noreferrer">{salon.contact.instagram}</a></div></div><div className="footer-bottom"><span>© 2025 Ruang Rona. Salon & Beauty House.</span><span>Harga dapat berubah sesuai panjang, ketebalan, dan kondisi rambut setelah konsultasi.</span></div></footer>; }
