export type Service = { slug: string; name: string; label: string; description: string; useCases: string[]; includes: string[]; time: string; price: string; notes: string[] };

export const services: Service[] = [
  { slug: "kiloan", name: "Laundry kiloan", label: "Cuci harian", description: "Untuk pakaian sehari-hari yang ingin kembali bersih, kering, dan siap masuk lemari.", useCases: ["Rumah tangga", "Anak kost", "Pekerja sibuk"], includes: ["Penimbangan di awal", "Cuci sesuai pilihan layanan", "Lipat atau setrika sesuai pesanan"], time: "[Estimasi proses]", price: "Mulai RpXX.XXX", notes: ["Pakaian dengan kebutuhan khusus sebaiknya disebutkan saat pemesanan."] },
  { slug: "setrika", name: "Setrika", label: "Rapi tanpa mencuci ulang", description: "Pakaian bersih Anda kami bantu rapikan agar siap dipakai atau disimpan.", useCases: ["Keluarga dengan cucian menumpuk", "Kemeja kerja", "Anak kost"], includes: ["Pemeriksaan catatan pelanggan", "Setrika sesuai jenis pakaian", "Lipat atau gantung sesuai kesepakatan"], time: "[Estimasi proses]", price: "Mulai RpXX.XXX", notes: ["Pakaian harus sudah bersih dan kering saat dititipkan."] },
  { slug: "satuan", name: "Laundry satuan", label: "Untuk barang tertentu", description: "Perawatan per potong untuk pakaian atau barang yang tidak cocok dihitung kiloan.", useCases: ["Jaket dan jas", "Sepatu atau tas", "Kain khusus"], includes: ["Pencatatan jenis barang", "Catatan kebutuhan khusus", "Konfirmasi harga sebelum diproses"], time: "[Estimasi proses]", price: "Mulai RpXX.XXX", notes: ["Hasil dan metode bergantung pada bahan serta kondisi barang."] },
  { slug: "bedding", name: "Bedding & tekstil rumah", label: "Barang berukuran besar", description: "Untuk sprei, bed cover, selimut, dan tekstil rumah yang membutuhkan ruang lebih saat dicuci.", useCases: ["Rumah tangga", "Kost dan apartemen", "Homestay"], includes: ["Pencatatan per barang", "Pemeriksaan bahan dan label", "Konfirmasi penanganan bila diperlukan"], time: "[Estimasi proses]", price: "Mulai RpXX.XXX", notes: ["Ukuran, bahan, dan kondisi barang dapat memengaruhi harga."] },
  { slug: "express", name: "Express service", label: "Saat perlu lebih cepat", description: "Pilihan proses yang lebih cepat jika kapasitas dan jenis barang memungkinkan.", useCases: ["Kebutuhan kerja mendadak", "Tamu homestay", "Pakaian untuk perjalanan"], includes: ["Cek kapasitas sebelum menerima", "Konfirmasi biaya express", "Pemberitahuan jika ada perubahan"], time: "[Estimasi express]", price: "Mulai RpXX.XXX", notes: ["Tidak semua bahan dan jenis barang dapat diproses express."] },
  { slug: "usaha", name: "Laundry untuk usaha", label: "Pesanan berulang", description: "Pengaturan yang lebih rapi untuk homestay, salon, spa, kafe, dan usaha kecil.", useCases: ["Homestay dan guesthouse", "Salon dan spa", "Kafe dan usaha kecil"], includes: ["Pembahasan kebutuhan rutin", "Pencatatan per pengiriman", "Jadwal dan harga dibicarakan di awal"], time: "[Sesuai kesepakatan]", price: "[Penawaran setelah diskusi]", notes: ["Hubungi kami agar kebutuhan, volume, dan jadwal bisa dibahas dengan wajar."] },
];

