import type { Metadata } from "next";
import { Manrope, Newsreader } from "next/font/google";
import { SiteHeader, MobileBookingBar } from "@/components/navigation";
import { Footer } from "@/components/ui";
import { salon } from "@/data/salon";
import "./globals.css";

const manrope = Manrope({ variable: "--font-manrope", subsets: ["latin"], display: "swap" });
const newsreader = Newsreader({ variable: "--font-newsreader", subsets: ["latin"], display: "swap" });
export const metadata: Metadata = { metadataBase: new URL("https://ruangrona.example"), title: { default: "Ruang Rona | Salon dan Beauty House di Jakarta", template: "%s | Ruang Rona" }, description: "Perawatan rambut, wajah, kuku, dan relaksasi di salon yang hangat dan nyaman. Lihat layanan Ruang Rona dan reservasi melalui WhatsApp.", alternates: { canonical: "/" }, openGraph: { type: "website", locale: "id_ID", siteName: "Ruang Rona", title: "Ruang Rona | Salon dan Beauty House di Jakarta", description: "Perawatan rambut, wajah, kuku, dan relaksasi di salon yang hangat dan nyaman." }, twitter: { card: "summary_large_image", title: "Ruang Rona | Salon dan Beauty House di Jakarta", description: "Perawatan rambut, wajah, kuku, dan relaksasi di salon yang hangat dan nyaman." } };
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) { const jsonLd = { "@context": "https://schema.org", "@type": "BeautySalon", name: salon.brand.name, description: "Salon dan beauty house yang hangat di Jakarta Selatan.", url: "https://ruangrona.example", telephone: salon.contact.phone, priceRange: "RpRp", address: { "@type": "PostalAddress", streetAddress: salon.contact.address, addressLocality: "Jakarta Selatan", addressCountry: "ID" }, geo: { "@type": "GeoCoordinates", latitude: salon.contact.coordinates.latitude, longitude: salon.contact.coordinates.longitude }, openingHoursSpecification: salon.hours.map(([day, time]) => ({ "@type": "OpeningHoursSpecification", dayOfWeek: day, opens: time.split("–")[0], closes: time.split("–")[1] })) }; return <html lang="id" className={`${manrope.variable} ${newsreader.variable}`}><body><aside className="demo-notice" aria-label="Pemberitahuan demo"><span>DEMO / PORTFOLIO</span><p>Ini adalah situs demo untuk Ruang Rona, dibuat oleh Getstore.</p><a href="https://getstore.my.id" target="_blank" rel="noreferrer">getstore.my.id ↗</a></aside><SiteHeader /><main>{children}</main><Footer /><MobileBookingBar /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /></body></html>; }
