import Link from "next/link";
import Image from "next/image";
import { salon } from "@/data/salon";
import { WhatsAppButton } from "@/components/brand";
import { Eyebrow, FeaturedTreatments, ImageWithCaption, JournalPreview, SectionIntro, Testimonials } from "@/components/ui";

export default function Home() { return <div className="page-shell">
  <section className="hero"><div className="hero-copy"><Eyebrow>{salon.brand.locationLabel}</Eyebrow><h1>Waktu kecil untuk merawat diri, perubahan besar untuk menjalani hari.</h1><p>Perawatan rambut, wajah, kuku, dan relaksasi dalam ruang yang hangat, bersih, dan tanpa tergesa-gesa.</p><div className="hero-actions"><Link className="button button-primary" href="/layanan">Pilih Perawatan <span>↗</span></Link><WhatsAppButton /></div><p className="hero-note">Reservasi disarankan agar waktu perawatan lebih nyaman.</p></div><div className="hero-visual"><ImageWithCaption src="/images/hero-salon.png" alt="Stylist dan pelanggan perempuan Indonesia sedang berkonsultasi di salon" caption="Ruang untuk konsultasi yang jujur." /><div className="hero-stamp">pelan-pelan<br />jadi rona</div></div></section>
  <section className="section intro-section"><SectionIntro eyebrow="Cara kami bekerja" title="Bukan sekadar selesai dirawat. Kami ingin Anda merasa kembali menjadi diri sendiri." /><div className="intro-copy"><p>Sebelum memulai, kami mendengarkan. Rekomendasi kami dibuat berdasarkan kebutuhan, rutinitas, dan waktu yang Anda punya—bukan untuk menambah layanan yang tidak perlu.</p><small>Alat dan workstation dibersihkan dengan tertib. Untuk pelanggan berhijab, area privat atau folding screen dapat diminta saat reservasi sesuai ketersediaan.</small></div></section>
  <section className="section"><SectionIntro eyebrow="Pilihan perawatan" title="Yang Anda butuhkan, tanpa daftar yang membingungkan." copy="Mulai dari perawatan rutin sampai persiapan untuk momen penting. Harga awal ditulis terbuka agar percakapan di salon terasa lebih mudah." /><FeaturedTreatments /><div className="section-end-link"><Link href="/layanan" className="text-link">Lihat seluruh menu layanan ↗</Link></div></section>
  <section className="section section-dark"><div className="page-shell"><SectionIntro eyebrow="Signature experience" title="Datang dengan rutinitas. Pulang dengan ruang di kepala." copy="Empat langkah sederhana yang membuat setiap kunjungan terasa lebih personal." /><div className="sequence">{[["01","Datang","Disambut tanpa perlu merasa harus terlihat siap.","/images/hero-salon.png","Pelanggan tiba di ruang salon"],["02","Konsultasi","Membicarakan yang Anda mau dan apa yang realistis.","/images/consultation-detail.png","Stylist menunjukkan pilihan warna rambut"],["03","Dirawat","Waktu untuk duduk, bernapas, dan mempercayakan proses.","/images/hair-spa.png","Perawatan rambut dengan handuk hangat"],["04","Pulang lebih ringan","Membawa pulang perawatan yang terasa pas.","/images/salon-interior.png","Interior salon yang tenang dan tertata"]].map(([n,title,copy,image,alt]) => <div className="sequence-item" key={n}><div className="sequence-image"><Image src={image} alt={alt} fill sizes="(max-width: 600px) 100vw, 25vw" /></div><span>{n}</span><h3>{title}</h3><p>{copy}</p></div>)}</div></div></section>
  <section className="section"><div className="split-feature"><div className="feature-copy"><Eyebrow>Privasi & kenyamanan</Eyebrow><h2>Nyaman untuk membuka hijab, tenang selama perawatan.</h2><p>Ruang Rona terbuka untuk siapa pun yang ingin dirawat dengan tenang. Jika Anda membutuhkan area yang lebih privat, sampaikan saat reservasi agar kami dapat menyiapkan folding screen atau area yang tersedia.</p><Link href="/reservasi" className="text-link">Tanyakan saat reservasi ↗</Link></div><ImageWithCaption src="/images/hijab-private-area.png" alt="Area privat salon dengan folding screen untuk pelanggan berhijab" caption="Privasi dapat diminta saat reservasi." /> </div></section>
  <section className="section section-dark"><div className="page-shell"><div className="split-feature"><ImageWithCaption src="/images/salon-interior.png" alt="Suasana ruang salon Ruang Rona dengan cermin lengkung, kursi blush, dan cahaya hangat" caption="Suasana ruang · lega, hangat, dan tertata." /><div className="feature-copy"><Eyebrow>Suasana ruang</Eyebrow><h2>Rapi, hangat, dan cukup tenang untuk mendengar diri sendiri.</h2><p>Detail kecil kami jaga: peralatan bersih, musik yang tidak mengganggu, cahaya hangat, jadwal yang ramah waktu ibadah, serta air putih atau teh hangat untuk menemani.</p><ul className="feature-points"><li>Stasiun kerja tertata dan mudah dibersihkan</li><li>Area konsultasi dengan waktu yang cukup</li><li>Permintaan privasi dibicarakan sejak awal</li></ul></div></div></div></section>
  <section className="section"><SectionIntro eyebrow="Catatan dari pelanggan" title="Pengalaman yang masih kami bangun, satu kunjungan demi satu." copy="Berikut contoh format suara pelanggan. Kami akan menggantinya dengan testimoni terverifikasi sebelum situs dipublikasikan." /><Testimonials /></section>
  <section className="section"><SectionIntro eyebrow="Dari jurnal" title="Sedikit pengetahuan sebelum Anda memilih." /><JournalPreview /></section>
  <section className="section section-dark cta-section"><div className="cta-band"><div><Eyebrow>Langkah berikutnya</Eyebrow><h2>Sudah tahu perawatan yang Anda butuhkan?</h2></div><div className="hero-actions"><WhatsAppButton label="Konsultasi via WhatsApp" /><Link className="button button-secondary" href="/layanan">Lihat menu layanan <span>↗</span></Link></div></div></section>
</div>; }
