import Image from "next/image";
import Link from "next/link";
import PageShell from "@/components/PageShell";
import SectionHeading from "@/components/SectionHeading";
import ServiceCard from "@/components/ServiceCard";
import PriceTable from "@/components/PriceTable";
import CTA from "@/components/CTA";
import { services } from "@/content/services";
import { areas } from "@/content/areas";
import { faqPreview } from "@/content/faqs";
import { testimonials } from "@/content/testimonials";
import { whatsappUrl } from "@/lib/whatsapp";

export default function Home() { return <PageShell>
  <section className="hero"><div className="shell hero-grid"><div className="hero-copy"><p className="eyebrow">Laundry harian untuk hidup yang sudah cukup sibuk.</p><h1>Baju bersih,<br /><i>jadwal tetap jalan.</i></h1><p className="hero-text">Laundry kiloan, satuan, setrika, dan layanan ekspres dengan antar-jemput di area terdekat. Harga terlihat dari awal. Status pesanan dikabarkan tanpa harus Anda kejar.</p><div className="hero-actions"><a className="button" href={whatsappUrl()}>Pesan via WhatsApp ↗</a><Link className="text-link" href="/layanan">Lihat layanan & harga <span aria-hidden="true">→</span></Link></div><p className="micro-note"><span aria-hidden="true">✳</span> Konfirmasi jadwal penjemputan dilakukan melalui WhatsApp.</p></div><div className="hero-art" aria-label="Pakaian bersih terlipat dalam keranjang laundry"><div className="art-frame"><Image className="hero-photo" src="/images/laundry-clothes-basket.png" alt="Kemeja dan pakaian bersih berwarna biru, putih, dan kuning di dalam keranjang anyaman" fill priority sizes="(max-width: 640px) 100vw, 47vw" /><div className="paper-tag"><span>ORDER NOTE</span><strong>PR—024</strong><small>cuci · lipat · antar</small></div><div className="stitch-line"></div><div className="art-caption">pakaian sehari-hari,<br />ditangani satu per satu</div></div></div></div></section>
  <section className="commitments"><div className="shell commitment-grid">{["Pesanan dicatat per pelanggan", "Harga dikonfirmasi di awal", "Pilihan tanpa pewangi tersedia", "Perubahan jadwal segera dikabarkan"].map((item, i) => <div className="commitment" key={item}><span>0{i + 1}</span><p>{item}</p></div>)}</div></section>
  <section className="section section-linen"><div className="shell"><SectionHeading eyebrow="Yang paling sering dipesan" title="Pilih cara yang paling masuk akal untuk minggu Anda." intro="Mulai dari cucian harian sampai satu potong pakaian yang perlu perhatian lebih." /><div className="service-grid">{services.slice(0, 4).map((service, i) => <ServiceCard key={service.slug} service={service} index={i} />)}</div></div></section>
  <section className="section process-preview"><div className="shell process-layout"><div className="process-stamp"><span>HOW IT<br />WORKS</span><strong>04</strong></div><div><SectionHeading title="Dari pesan singkat sampai kembali ke lemari." intro="Anda cukup mengirim kebutuhan dasar. Kami bantu merapikan bagian yang berikutnya." /><div className="process-list">{["Kirim lokasi dan kebutuhan", "Kami konfirmasi jadwal", "Cucian dicatat dan diproses", "Pesanan dikirim kembali"].map((item, i) => <div className="process-row" key={item}><b>0{i + 1}</b><div><h3>{item}</h3><p>{["Sebutkan area, jenis layanan, dan perkiraan jumlah cucian.", "Jadwal penjemputan dan perkiraan biaya dibicarakan melalui WhatsApp.", "Barang atau berat dicatat agar pesanan mudah dicek kembali.", "Kami memberi kabar saat pesanan siap diantar atau diambil."][i]}</p></div></div>)}</div></div></div></section>
  <section className="section care-section"><div className="shell care-layout"><div className="care-copy"><SectionHeading eyebrow="Standar perawatan" title="Yang kami jaga bukan hanya bersihnya." intro="Setiap pesanan perlu jejak yang jelas. Ini cara kami mengurangi salah catat dan kejutan di akhir." /><Image className="section-photo care-photo" src="/images/garment-care-check.png" alt="Tangan memeriksa label perawatan pada kemeja biru di meja kerja laundry" width={900} height={600} sizes="(max-width: 640px) 100vw, 42vw" /><Link className="text-link" href="/cara-kerja">Lihat cara kerja lengkap →</Link></div><div className="care-list">{["Identitas pesanan", "Pemeriksaan saku dasar", "Pemisahan sesuai layanan", "Catatan khusus", "Konfirmasi jumlah atau berat", "Kabar saat selesai"].map((item, i) => <div key={item}><span>{String(i + 1).padStart(2, "0")}</span><p>{item}</p></div>)}</div></div></section>
  <section className="section audience-section"><div className="shell audience-layout"><div><SectionHeading title="Untuk ritme hidup yang berbeda-beda." /><p className="audience-intro">Tidak semua orang punya waktu, ruang, atau tenaga untuk mencuci dan menjemur. Kami menyesuaikan pembicaraan dari kebutuhan yang nyata.</p></div><div className="audience-list">{["Rumah tangga", "Anak kost", "Pekerja sibuk", "Homestay dan guesthouse", "Salon, spa, dan usaha kecil"].map((item, i) => <div key={item}><span>{String(i + 1).padStart(2, "0")}</span><h3>{item}</h3></div>)}<Link className="text-link" href="/layanan#usaha">Bicarakan laundry rutin untuk usaha →</Link></div></div></section>
  <section className="section pricing-section"><div className="shell"><SectionHeading eyebrow="Harga yang dibicarakan di awal" title="Sederhana untuk dibaca, terbuka untuk dicek." intro="Angka berikut adalah data bisnis yang perlu diganti dan dikonfirmasi sebelum situs dipublikasikan." /><PriceTable /><p className="table-note">Harga akhir mengikuti berat, jenis barang, layanan tambahan, dan area penjemputan. Kami akan mengonfirmasinya sebelum pesanan diproses.</p></div></section>
  <section className="area-preview"><div className="shell area-preview-inner"><div><p className="eyebrow">Penjemputan lokal</p><h2>Mulai dari alamat Anda.</h2><p>Area berikut masih berupa contoh. Kirim alamat untuk memastikan apakah jadwal penjemputan tersedia.</p></div><div className="area-side"><div className="area-chips">{areas.map((area) => <span key={area}>{area}</span>)}</div><Link className="button button-outline" href="/area-layanan">Cek area layanan ↗</Link></div></div></section>
  {testimonials.length > 0 && <section className="section testimonials"><div className="shell"><SectionHeading title="Cerita dari pelanggan" /><div>{testimonials.map((item) => <blockquote key={item.name}>“{item.quote}”<cite>{item.name} · {item.context}</cite></blockquote>)}</div></div></section>}
  <section className="section faq-preview"><div className="shell faq-preview-layout"><SectionHeading eyebrow="Pertanyaan yang sering muncul" title="Sebelum Anda menitipkan." /><div className="faq-preview-list">{faqPreview.map((item, i) => <Link href={`/faq#faq-${i}`} key={item.q}><span>{item.q}</span><b aria-hidden="true">↗</b></Link>)}</div><Link className="text-link" href="/faq">Lihat semua pertanyaan →</Link></div></section>
  <CTA />
</PageShell> }
