import Image from "next/image";
import Link from "next/link";
import type { MenuItem } from "@/data/menu";
import { site } from "@/data/site";
export function AnnouncementBar(){return <div className="bg-sambal px-4 py-2 text-center text-xs font-bold text-paper">Jadwal nobar pekan ini sudah dibuka. Kursi lesehan terbatas.</div>}
export function SectionHeading({eyebrow,title,copy,href,link}:{eyebrow:string;title:string;copy?:string;href?:string;link?:string}){return <div className="flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">{eyebrow}</p><h2 className="display mt-3 max-w-2xl text-4xl leading-[.95] sm:text-5xl">{title}</h2>{copy&&<p className="mt-4 max-w-xl text-sm leading-6 text-muted">{copy}</p>}</div>{href&&link&&<Link className="text-sm font-extrabold text-sambal underline decoration-1 underline-offset-4" href={href}>{link} →</Link>}</div>}
export function AvailabilityBadge({status}:{status:string}){return <span className={`inline-flex border px-2 py-1 text-[10px] font-extrabold uppercase tracking-wider ${status==="tersedia"?"border-leaf text-leaf":status==="penuh"?"border-sambal text-sambal":"border-warung text-[#9a690e]"}`}>{status}</span>}
export function MenuCard({item}:{item:MenuItem}){return <article><div className="photo aspect-[4/3] border border-charcoal/20"><Image src={item.image} alt={`${item.name}, ${item.description}`} fill sizes="(max-width: 768px) 48vw, 31vw"/><div className="absolute left-2 top-2 z-10 flex gap-1">{item.umkm&&<span className="bg-leaf px-2 py-1 text-[9px] font-bold uppercase tracking-wider text-paper">Titipan UMKM</span>}</div></div><div className="mt-3 flex items-start justify-between gap-2"><h3 className="text-sm font-extrabold leading-5 sm:text-base">{item.name}</h3><span className="shrink-0 text-sm font-extrabold tabular text-sambal">Rp{item.price.toLocaleString("id-ID")}</span></div><p className="mt-1 text-xs leading-5 text-muted">{item.description}</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-muted">{item.vegetarian?"Vegetarian":"Lauk"} · {item.spice}</p></article>}
export function WhatsAppButton(){return <a className="button button-light" href={`https://wa.me/${site.whatsapp}?text=Halo%20Lungguh,%20saya%20mau%20bertanya.`} target="_blank" rel="noreferrer">Tanya lewat WhatsApp</a>}
export function PageIntro({eyebrow,title,copy}:{eyebrow:string;title:string;copy:string}){return <div className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1 className="display mt-5">{title}</h1><p className="prose-copy mt-6 text-lg">{copy}</p></div></div>}
