"use client";
import Link from "next/link";
import Image from "next/image";
import { ArrowUpRight, Baby, Brain, CalendarDays, Check, ChevronDown, HeartPulse, MapPin, Menu, Phone, Search, ShieldCheck, Stethoscope, UsersRound, X, Activity, PersonStanding, Printer, Sofa, Utensils, Shirt, Leaf, Truck, Wrench, Megaphone, BadgeCheck } from "lucide-react";
import type { Doctor, Service } from "@/lib/data";
import { hospital } from "@/lib/data";
import { cn } from "@/lib/utils";
import type React from "react";
import { useState } from "react";

export function Logo({ light = false }: { light?: boolean }) { return <Link href="/" className={cn("flex items-center gap-3", light ? "text-white" : "text-[#123F42]")} aria-label="Nusa Medika, beranda"><span className="logo-mark" aria-hidden="true"><span /></span><span><strong className="block text-[15px] tracking-[.08em] leading-none">NUSA MEDIKA</strong><small className={cn("mt-1 block text-[9px] tracking-[.08em]", light ? "text-white/65" : "text-[#5F6A67]")}>RUMAH SAKIT UMUM</small></span></Link>; }

export function UtilityBar() { return <div className="bg-[#123F42] text-white"><div className="site-container flex min-h-9 items-center justify-between gap-4 text-[11px] font-medium"><div className="flex items-center gap-5"><span className="flex items-center gap-2"><span className="status-dot" /> IGD 24 Jam <strong className="text-[#F5C3A9]">{hospital.emergency}</strong></span><span className="hidden sm:inline-flex items-center gap-1.5 text-white/70"><MapPin size={13} /> Kota Sentosa</span></div><div className="hidden items-center gap-5 sm:flex"><Link href="/kontak#lokasi" className="text-white/75 hover:text-white">Lokasi</Link><Link href="/kontak#informasi-pasien" className="text-white/75 hover:text-white">Informasi Pasien</Link></div></div></div> }

export function SiteHeader() { return <><UtilityBar /><header className="sticky top-0 z-30 border-b border-[#D7DDD8]/90 bg-[#FCFBF8]/95 backdrop-blur"><div className="site-container flex h-[72px] items-center justify-between gap-6"><Logo /><nav className="hidden items-center gap-6 lg:flex" aria-label="Navigasi utama"><Link href="/" className="nav-link">Beranda</Link><Link href="/layanan" className="nav-link">Layanan</Link><Link href="/dokter" className="nav-link">Dokter</Link><Link href="/mitra-nusa" className="nav-link">Mitra Nusa</Link><Link href="/tentang" className="nav-link">Tentang Kami</Link><Link href="/kontak" className="nav-link">Kontak</Link></nav><div className="flex items-center gap-2"><Link href="/dokter" className="hidden h-10 w-10 items-center justify-center text-[#123F42] hover:bg-[#F0F3EF] sm:flex" aria-label="Cari"><Search size={19} /></Link><Link href="/kontak#janji" className="button button-primary hidden sm:inline-flex">Buat Janji <ArrowUpRight size={16} /></Link><MobileNavigation /></div></div></header></> }

export function MobileNavigation() { const [open, setOpen] = useState(false); return <div className="lg:hidden"><button type="button" className="button button-quiet h-10 w-10 px-0" onClick={() => setOpen(v => !v)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open ? "Tutup menu" : "Buka menu"}>{open ? <X size={20} /> : <Menu size={20} />}</button>{open && <div id="mobile-menu" className="absolute inset-x-0 top-[72px] border-b border-[#D7DDD8] bg-[#FCFBF8] p-5 shadow-[0_14px_30px_rgba(18,63,66,.08)]"><nav className="grid gap-1" aria-label="Navigasi mobile">{[["Beranda", "/"], ["Layanan", "/layanan"], ["Dokter", "/dokter"], ["Mitra Nusa", "/mitra-nusa"], ["Tentang Kami", "/tentang"], ["Kontak", "/kontak"]].map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)} className="border-b border-[#D7DDD8] py-3 text-sm font-semibold text-[#123F42]">{label}</Link>)}</nav><Link href="tel:0215550119" className="mt-4 flex items-center gap-2 text-sm font-semibold text-[#B85E3F]"><Phone size={16} /> Hubungi IGD 24 jam</Link></div>}</div> }

export function SiteFooter() { return <footer className="bg-[#123F42] text-white"><div className="site-container grid gap-12 py-16 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><Logo light /><p className="mt-6 max-w-xs text-sm leading-7 text-white/68">Rumah sakit umum dan pusat kesehatan keluarga untuk Kota Sentosa dan sekitarnya.</p><p className="mt-7 text-sm leading-7 text-white/80">{hospital.address}</p></div><div><p className="footer-label">Hubungi</p><div className="mt-5 grid gap-3 text-sm text-white/75"><a href={`tel:${hospital.emergency}`} className="hover:text-white">IGD 24 jam<br /><strong className="text-white">{hospital.emergency}</strong></a><a href={`tel:${hospital.phone}`} className="hover:text-white">Umum<br /><strong className="text-white">{hospital.phone}</strong></a><a href={`mailto:${hospital.email}`} className="hover:text-white">{hospital.email}</a></div></div><div><p className="footer-label">Jelajah</p><div className="mt-5 grid gap-3 text-sm text-white/75"><Link href="/layanan">Layanan medis</Link><Link href="/dokter">Cari dokter</Link><Link href="/tentang">Tentang kami</Link><Link href="/mitra-nusa">Mitra Nusa</Link><Link href="/kontak">Kontak</Link></div></div><div><p className="footer-label">Informasi</p><div className="mt-5 grid gap-3 text-sm text-white/75"><Link href="/kontak#informasi-pasien">Informasi pasien</Link><Link href="/kontak#jam-kunjung">Jam kunjung</Link><Link href="/privacy">Pemberitahuan privasi</Link><span>Instagram · LinkedIn</span></div></div></div><div className="border-t border-white/15"><div className="site-container flex flex-col gap-3 py-5 text-xs leading-5 text-white/55 sm:flex-row sm:items-center sm:justify-between"><span>© 2025 Nusa Medika. Seluruh nilai dan profil pada situs ini adalah contoh.</span><span>Konten demo · Bukan pengganti konsultasi medis.</span></div></div></footer> }

export function Container({ children, className }: { children: React.ReactNode; className?: string }) { return <div className={cn("site-container", className)}>{children}</div> }
export function SectionHeading({ eyebrow, title, children, className }: { eyebrow?: string; title: string; children?: React.ReactNode; className?: string }) { return <div className={cn("mb-9", className)}>{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h2 className="section-title">{title}</h2>{children && <p className="mt-4 max-w-2xl text-[15px] leading-7 text-[#5F6A67]">{children}</p>}</div> }
export function Breadcrumbs({ current }: { current: string }) { return <nav aria-label="Breadcrumb" className="mb-8 text-xs text-[#5F6A67]"><Link href="/" className="hover:text-[#123F42]">Beranda</Link><span className="mx-2">/</span><span className="text-[#123F42]">{current}</span></nav> }
export function Button({ children, href, variant = "primary", type = "button", className }: { children: React.ReactNode; href?: string; variant?: "primary" | "secondary" | "quiet"; type?: "button" | "submit"; className?: string }) { const classes = cn("button", `button-${variant}`, className); return href ? <Link href={href} className={classes}>{children}</Link> : <button type={type} className={classes}>{children}</button> }
export function DemoDataNotice({ children = "Data pada halaman ini merupakan contoh untuk demonstrasi dan perlu diganti sebelum digunakan secara operasional." }: { children?: React.ReactNode }) { return <div className="demo-notice"><ShieldCheck size={17} /> <span>{children}</span></div> }
export function EmergencyPanel() { return <aside className="emergency-panel"><div className="flex items-start gap-4"><div className="emergency-icon"><Phone size={20} /></div><div><p className="eyebrow text-[#F5C3A9]">Untuk keadaan darurat</p><h2 className="mt-2 font-display text-2xl font-semibold text-white">IGD tersedia 24 jam.</h2><p className="mt-2 max-w-xl text-sm leading-6 text-white/72">Jangan gunakan formulir online untuk keadaan darurat. Hubungi nomor IGD atau datang langsung ke rumah sakit.</p></div></div><a href={`tel:${hospital.emergency}`} className="button button-terra mt-6 sm:mt-0">Hubungi IGD <Phone size={16} /></a></aside> }

const serviceIcons: Record<string, React.ElementType> = { heart: HeartPulse, baby: Baby, activity: Activity, stethoscope: Stethoscope, brain: Brain, "person-standing": PersonStanding };
export function ServiceCard({ service, compact = false }: { service: Service; compact?: boolean }) { const Icon = serviceIcons[service.icon] ?? Stethoscope; return <article className={cn("service-card", compact && "service-card-compact")}><div className="service-icon"><Icon size={22} strokeWidth={1.7} /></div><div className="flex-1"><h3 className="text-lg font-semibold text-[#123F42]">{service.name}</h3><p className="mt-2 text-sm leading-6 text-[#5F6A67]">{service.description}</p>{!compact && <div className="mt-5 grid gap-2 border-t border-[#D7DDD8] pt-4 text-xs leading-5 text-[#5F6A67]"><span><strong className="text-[#123F42]">Untuk:</strong> {service.forWhom}</span><span><strong className="text-[#123F42]">Jadwal:</strong> {service.days}</span></div>}</div></article> }
export function ScheduleBadge({ availability }: { availability: Doctor["availability"] }) { return <span className={cn("schedule-badge", availability === "Penuh" && "schedule-full", availability === "Terbatas" && "schedule-limited")}><span />{availability}</span> }
export function DoctorCard({ doctor }: { doctor: Doctor }) { return <article className="doctor-card"><div className="doctor-photo"><Image src={doctor.image} alt={`Potret ${doctor.name}`} fill sizes="(max-width: 768px) 100vw, 280px" /></div><div className="p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[#B85E3F]">{doctor.specialty}</p><h3 className="mt-1 text-lg font-semibold leading-snug text-[#123F42]">{doctor.name}</h3></div><ScheduleBadge availability={doctor.availability} /></div><p className="mt-3 text-sm leading-6 text-[#5F6A67]">{doctor.focus}</p><div className="mt-5 grid gap-2 text-xs text-[#5F6A67]"><span className="flex gap-2"><CalendarDays size={15} className="text-[#1E6767]" /> {doctor.schedule}</span><span className="flex gap-2"><MapPin size={15} className="text-[#1E6767]" /> {doctor.location}</span><span className="flex gap-2"><UsersRound size={15} className="text-[#1E6767]" /> {doctor.languages.join(" · ")}</span></div><div className="mt-5 flex gap-4 border-t border-[#D7DDD8] pt-4"><Link href={`/dokter?nama=${doctor.id}`} className="text-sm font-semibold text-[#123F42] hover:text-[#B85E3F]">Lihat Jadwal</Link><Link href="/kontak#janji" className="text-sm font-semibold text-[#1E6767] hover:text-[#B85E3F]">Buat Janji <ArrowUpRight className="inline" size={14} /></Link></div></div></article> }
export function TrustMetric({ value, label }: { value: string; label: string }) { return <div className="trust-metric"><strong>{value}</strong><span>{label}</span></div> }
export function ProcessSteps({ steps }: { steps: string[] }) { return <ol className="process-steps">{steps.map((step, index) => <li key={step}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{step}</strong><p>{index === 0 ? "Gunakan direktori layanan atau dokter untuk memulai." : index === 1 ? "Pilih waktu yang masih tersedia untuk kunjungan." : index === 2 ? "Siapkan identitas dan informasi yang relevan." : "Datang sedikit lebih awal agar proses berjalan lancar."}</p></div></li>)}</ol> }
export function ArticleCard({ article, index = 0 }: { article: (typeof import("@/lib/data").articles)[number]; index?: number }) { return <article className={cn("article-card", index === 0 && "article-card-featured")}><div className={cn("article-art", `article-art-${index}`)}><span>{index === 0 ? "Catatan pasien" : index === 1 ? "Pemeriksaan rutin" : "Kesehatan keluarga"}</span></div><div className="p-5"><p className="text-xs font-semibold text-[#B85E3F]">{article.category} · {article.read}</p><h3 className="mt-2 text-lg font-semibold leading-snug text-[#123F42]">{article.title}</h3><p className="mt-3 text-sm leading-6 text-[#5F6A67]">{article.excerpt}</p><p className="mt-5 text-sm font-semibold text-[#1E6767]">Baca informasi <ArrowUpRight className="inline" size={15} /></p></div></article> }
export function PartnerCategoryCard({ label }: { label: string }) { const map: Record<string, React.ElementType> = { "Konsumsi dan katering": Utensils, "Tekstil, linen, dan seragam": Shirt, "Produk kebersihan non-medis": ShieldCheck, "Furnitur dan interior": Sofa, "Percetakan": Printer, "Hampers dan merchandise": BadgeCheck, "Tanaman dan lanskap": Leaf, "Dokumentasi dan acara": Megaphone, "Logistik lokal": Truck, "Jasa perawatan fasilitas": Wrench }; const Icon = map[label] ?? Check; return <div className="partner-category"><Icon size={19} /><span>{label}</span></div> }
export function FAQAccordion({ items }: { items: string[][] }) { const [open, setOpen] = useState<number | null>(null); return <div className="faq-list">{items.map(([question, answer], index) => <div key={question} className="faq-item"><button type="button" className="faq-trigger" onClick={() => setOpen(open === index ? null : index)} aria-expanded={open === index}><span>{question}</span><ChevronDown size={18} className={cn("transition-transform", open === index && "rotate-180")} /></button>{open === index && <div className="faq-answer"><p>{answer}</p></div>}</div>)}</div> }
export function EmptyState({ onReset }: { onReset?: () => void }) { return <div className="empty-state"><Search size={25} /><h3>Tidak ada dokter yang sesuai</h3><p>Coba ubah kata kunci atau longgarkan pilihan filter.</p>{onReset && <button onClick={onReset} className="text-sm font-semibold text-[#1E6767] underline underline-offset-4">Reset filter</button>}</div> }
export function FormField({ label, name, type = "text", required = false, placeholder, value, onChange, error, help }: { label: string; name: string; type?: string; required?: boolean; placeholder?: string; value?: string; onChange?: (e: React.ChangeEvent<HTMLInputElement>) => void; error?: string; help?: string }) { return <div className="form-field"><label htmlFor={name}>{label}{required && <span aria-hidden="true"> *</span>}</label><input id={name} name={name} type={type} required={required} placeholder={placeholder} value={value} onChange={onChange} aria-invalid={!!error} aria-describedby={error ? `${name}-error` : help ? `${name}-help` : undefined} />{help && <small id={`${name}-help`}>{help}</small>}{error && <small id={`${name}-error`} className="error-text">{error}</small>}</div> }
export function SelectField({ label, name, options, required = false }: { label: string; name: string; options: string[]; required?: boolean }) { return <div className="form-field"><label htmlFor={name}>{label}{required && <span aria-hidden="true"> *</span>}</label><select id={name} name={name} required={required}><option value="">Pilih salah satu</option>{options.map(option => <option key={option}>{option}</option>)}</select></div> }
export function CheckboxField({ name, children, required = false }: { name: string; children: React.ReactNode; required?: boolean }) { return <label className="checkbox-field"><input id={name} name={name} type="checkbox" required={required} /><span>{children}{required && <span aria-hidden="true"> *</span>}</span></label> }

export function PageIntro({ eyebrow, title, description, current }: { eyebrow?: string; title: string; description: string; current: string }) { return <div className="page-intro"><Breadcrumbs current={current} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Beranda", item: "https://nusa-medika.demo/" }, { "@type": "ListItem", position: 2, name: current }] }) }} />{eyebrow && <p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1><p>{description}</p></div> }
