import Image from "next/image";
import Link from "next/link";
import { business, barbers, gallery, services } from "@/data/business";
import { whatsappUrl } from "@/lib/whatsapp";
import SectionHeading from "@/components/section-heading";
import WhatsAppButton from "@/components/whatsapp-button";
import OpenStatus from "@/components/open-status";
import LocationPanel from "@/components/location-panel";

export default function Home() {
  return <div>
    <section className="site-container grid min-h-[590px] items-center gap-10 py-14 md:grid-cols-[.92fr_1.08fr] md:gap-16 md:py-16">
      <div><div className="eyebrow mb-5">Barbershop lingkungan, kerja serius.</div><h1 className="font-display text-[3.25rem] leading-[1.02] sm:text-6xl lg:text-[4.5rem]">Potongan yang cocok dipakai setelah keluar dari kursi.</h1><p className="mt-6 max-w-lg text-[15px] leading-7 muted">Kami tidak memaksakan tren ke setiap kepala. Ceritakan rutinitas, bentuk yang disukai, dan seberapa rajin Anda mau menatanya.</p><div className="mt-7 flex flex-wrap gap-3"><WhatsAppButton/><Link className="btn" href="/layanan">Lihat harga</Link></div><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 border-t hairline pt-5"><OpenStatus/><span className="text-sm muted">Mulai Rp55.000</span><span className="text-sm muted">{business.neighborhood}</span></div><p className="mt-4 text-xs muted">Estimasi balasan WhatsApp 5–15 menit saat jam buka.</p></div>
      <div className="relative md:pl-8"><div className="photo aspect-[4/5] md:aspect-[4/4.6]"><Image src="/images/pangkas-kala/hero-shop.webp" alt="Barber sedang merapikan rambut pelanggan di dalam Pangkas Kala" fill priority sizes="(max-width:768px) 100vw, 52vw" className="object-cover" /></div><div className="absolute -bottom-5 left-0 max-w-[220px] border hairline bg-bone p-4"><div className="font-display text-xl">Datang kusut,<br/>pulang beres.</div><p className="mt-2 text-xs leading-5 muted">Cilandak Barat · Jakarta Selatan</p></div></div>
    </section>
    <section className="border-y hairline bg-[#e8dfce] py-16 md:py-24"><div className="site-container grid gap-10 md:grid-cols-[.65fr_1.35fr] md:gap-16"><SectionHeading eyebrow="Menu utama" title="Harga jelas. Waktu masuk akal.">Empat layanan yang paling sering dipilih untuk kunjungan rutin.</SectionHeading><div><div className="service-list">{services.slice(0,4).map(s=><div className="service-row" key={s.name}><div><h3 className="font-display text-2xl">{s.name}</h3><p className="mt-1 text-sm muted">{s.duration} · {s.includes}</p></div><div className="font-display text-xl">Rp{s.price.toLocaleString("id-ID")}</div><WhatsAppButton label="Pilih" service={s.name} className="min-h-9 px-3 text-xs"/></div>)}</div><Link href="/layanan" className="mt-7 inline-flex border-b border-ink pb-1 text-sm font-bold">Lihat semua layanan →</Link></div></div></section>
    <section className="site-container grid gap-10 py-16 md:grid-cols-[1fr_1fr] md:items-center md:py-24"><div className="paper-grain border hairline p-8 md:p-12"><div className="font-display text-4xl leading-tight">Belum tahu cocoknya apa?</div><p className="mt-5 max-w-md text-[15px] leading-7">Duduk dulu. Kita bicarakan. Bawa foto referensi kalau ada—kami sesuaikan dengan jenis rambut, arah tumbuh, bentuk kepala, dan rutinitas harian.</p><a className="mt-7 inline-flex border-b border-ink pb-1 text-sm font-bold" href={whatsappUrl("Halo Pangkas Kala, saya mau konsultasi potongan rambut dulu.")} target="_blank" rel="noreferrer">Tanya barber di WhatsApp ↗</a></div><div className="md:pl-10"><SectionHeading title="Referensi boleh. Hasil tetap harus realistis.">Barber kami akan bilang jika bentuk yang Anda bawa perlu sedikit diubah supaya tetap enak dipakai setelah beberapa hari.</SectionHeading></div></section>
    <section className="border-y hairline py-16 md:py-24"><div className="site-container"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading eyebrow="Tiga cara kerja" title="Pilih barber yang nyambung."/><Link href="/barber" className="border-b border-ink pb-1 text-sm font-bold">Lihat profil barber →</Link></div><div className="mt-10 grid gap-8 md:grid-cols-3">{barbers.map((b,i)=><article key={b.name} className={i===1?"md:translate-y-8":""}><div className="photo aspect-[4/5]"><Image src={b.image} alt={`Potret ${b.name}, barber Pangkas Kala`} fill sizes="(max-width:768px) 100vw, 33vw" className="object-cover" /></div><div className="border-b hairline py-4"><div className="flex justify-between gap-3"><h3 className="font-display text-2xl">{b.name}</h3><span className="text-xs muted">{b.days}</span></div><p className="mt-1 text-sm text-tobacco">{b.role}</p><Link href="/barber" className="mt-4 inline-block text-sm font-bold underline underline-offset-4">Lihat cara kerjanya</Link></div></article>)}</div></div></section>
    <section className="site-container py-16 md:py-24"><div className="flex flex-wrap items-end justify-between gap-5"><SectionHeading title="Potongan yang pernah kami kerjakan.">Foto ini referensi, bukan janji hasil identik. Jenis rambut dan arah tumbuh selalu ikut bicara.</SectionHeading><Link href="/galeri" className="border-b border-ink pb-1 text-sm font-bold">Buka galeri →</Link></div><div className="mt-10 grid grid-cols-2 gap-3 md:grid-cols-4">{gallery.slice(0,6).map((g,i)=><div key={g.name} className={i===0?"col-span-2 row-span-2":""}><div className={`photo ${i===0?"aspect-[1/1]":"aspect-[4/3]"}`}><Image src={g.image} alt={g.alt} fill sizes="(max-width:768px) 50vw, 25vw" className="object-cover" /></div><div className="py-2 text-xs font-semibold">{g.name} <span className="font-normal muted">· {g.barber}</span></div></div>)}</div></section>
    <section className="bg-ink py-16 text-bone md:py-24"><div className="site-container"><SectionHeading eyebrow="Catatan pelanggan" title="Yang penting: didengar."/><div className="mt-10 grid gap-8 md:grid-cols-3">{["Arga beneran dengar instruksi saya, bukan langsung potong sesuai maunya. Setelah lima hari masih gampang diatur.","Harganya sama persis dengan menu. Saya booking lewat WhatsApp siang, sore sudah dapat kursi.","Bayu bantu ubah referensi yang saya bawa jadi lebih cocok untuk rambut saya. Hasilnya rapi tapi tidak kelihatan dipaksa."].map((t,i)=><blockquote key={i} className="border-t border-bone/20 pt-5 text-[15px] leading-7 text-bone/80">“{t}”<footer className="mt-5 text-xs text-bone/45">Pelanggan Pangkas Kala</footer></blockquote>)}</div></div></section>
    <section className="site-container py-16 md:py-24"><SectionHeading title="Mudah ditemukan, mudah dihubungi."/><div className="mt-10"><LocationPanel/></div></section>
    <section className="border-t hairline bg-[#d8cfbc] py-16 md:py-24"><div className="site-container flex flex-wrap items-end justify-between gap-8"><div><div className="eyebrow mb-3">Waktunya dirapikan?</div><h2 className="font-display text-4xl md:text-6xl">Sudah waktunya<br/>dirapikan?</h2></div><div className="flex flex-wrap gap-3"><WhatsAppButton label="Booking sekarang"/><a className="btn" href={whatsappUrl("Halo Pangkas Kala, saya mau tanya dulu soal potongan rambut.")} target="_blank" rel="noreferrer">Tanya dulu</a></div></div></section>
  </div>;
}
